services:
  - type: web
    name: bilancompetence-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd apps/backend && npm install && npm run build
    startCommand: cd apps/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://bilancompetence.vercel.app,https://bilancompetence-git-*.vercel.app
      - key: GEMINI_API_KEY
        sync: false
      - key: FRANCE_TRAVAIL_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false

