name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    name: Lint & Format Check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint || true

      - name: Check formatting
        run: npm run format:check || true

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test || true

      - name: Generate coverage
        run: npm run test:coverage || true

  build:
    runs-on: ubuntu-latest
    name: Build & Type Check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Type check
        run: npm run type-check || true

      - name: Build frontend
        run: cd apps/frontend && npm run build

      - name: Build backend
        run: cd apps/backend && npm run build

  security:
    runs-on: ubuntu-latest
    name: Security Scan
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit || true

  status:
    name: Build Status
    runs-on: ubuntu-latest
    needs: [lint-and-format, test, build, security]
    if: always()
    steps:
      - name: Check build status
        run: |
          echo "Pipeline completed"
          echo "Lint: ${{ needs.lint-and-format.result }}"
          echo "Test: ${{ needs.test.result }}"
          echo "Build: ${{ needs.build.result }}"
          echo "Security: ${{ needs.security.result }}"
