-- Migration 022: Seed RIASEC Test Questions
-- Date: 2025-10-25
-- Purpose: Insert RIASEC vocational interest test questions (48 questions, 8 per dimension)
-- Dependencies: 003_expand_assessment_questions.sql (assessment_questions table must exist)

-- RIASEC has 6 dimensions:
-- R: Realistic (Réaliste) - Practical, hands-on work
-- I: Investigative (Investigateur) - Analytical, scientific work
-- A: Artistic (Artistique) - Creative, expressive work
-- S: Social (Social) - Helping, teaching work
-- E: Enterprising (Entreprenant) - Leading, persuading work
-- C: Conventional (Conventionnel) - Organized, detail-oriented work

-- Each question is scored on a scale of 1-5:
-- 1 = Pas du tout intéressé(e), 5 = Très intéressé(e)

-- ============================================================================
-- DIMENSION 1: REALISTIC (R) - 8 questions
-- ============================================================================

INSERT INTO assessment_questions (id, assessment_id, step_number, section, question_text, question_type, options, "order", required, metadata) VALUES
('riasec-r-001'::uuid, NULL, 2, 'riasec_interests', 'Travailler avec des outils et des machines', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 1, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb),
('riasec-r-002'::uuid, NULL, 2, 'riasec_interests', 'Réparer des équipements ou des véhicules', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 2, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb),
('riasec-r-003'::uuid, NULL, 2, 'riasec_interests', 'Construire ou assembler des objets', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 3, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb),
('riasec-r-004'::uuid, NULL, 2, 'riasec_interests', 'Travailler en extérieur ou dans la nature', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 4, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb),
('riasec-r-005'::uuid, NULL, 2, 'riasec_interests', 'Utiliser mes mains pour créer des choses concrètes', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 5, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb),
('riasec-r-006'::uuid, NULL, 2, 'riasec_interests', 'Effectuer des tâches physiques et pratiques', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 6, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb),
('riasec-r-007'::uuid, NULL, 2, 'riasec_interests', 'Opérer des équipements techniques ou industriels', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 7, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb),
('riasec-r-008'::uuid, NULL, 2, 'riasec_interests', 'Travailler de manière autonome sur des projets concrets', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 8, true, '{"dimension": "R", "category": "Réaliste", "weight": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- DIMENSION 2: INVESTIGATIVE (I) - 8 questions
-- ============================================================================

INSERT INTO assessment_questions (id, assessment_id, step_number, section, question_text, question_type, options, "order", required, metadata) VALUES
('riasec-i-001'::uuid, NULL, 2, 'riasec_interests', 'Résoudre des problèmes complexes', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 9, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb),
('riasec-i-002'::uuid, NULL, 2, 'riasec_interests', 'Mener des recherches scientifiques', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 10, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb),
('riasec-i-003'::uuid, NULL, 2, 'riasec_interests', 'Analyser des données et des informations', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 11, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb),
('riasec-i-004'::uuid, NULL, 2, 'riasec_interests', 'Comprendre comment les choses fonctionnent', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 12, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb),
('riasec-i-005'::uuid, NULL, 2, 'riasec_interests', 'Effectuer des expériences et des tests', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 13, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb),
('riasec-i-006'::uuid, NULL, 2, 'riasec_interests', 'Étudier des théories et des concepts abstraits', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 14, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb),
('riasec-i-007'::uuid, NULL, 2, 'riasec_interests', 'Utiliser la logique et le raisonnement', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 15, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb),
('riasec-i-008'::uuid, NULL, 2, 'riasec_interests', 'Découvrir de nouvelles connaissances', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 16, true, '{"dimension": "I", "category": "Investigateur", "weight": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- DIMENSION 3: ARTISTIC (A) - 8 questions
-- ============================================================================

INSERT INTO assessment_questions (id, assessment_id, step_number, section, question_text, question_type, options, "order", required, metadata) VALUES
('riasec-a-001'::uuid, NULL, 2, 'riasec_interests', 'Créer des œuvres artistiques (peinture, dessin, sculpture)', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 17, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb),
('riasec-a-002'::uuid, NULL, 2, 'riasec_interests', 'Écrire des histoires, des poèmes ou des articles', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 18, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb),
('riasec-a-003'::uuid, NULL, 2, 'riasec_interests', 'Jouer d''un instrument de musique ou composer', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 19, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb),
('riasec-a-004'::uuid, NULL, 2, 'riasec_interests', 'Concevoir des designs ou des créations visuelles', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 20, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb),
('riasec-a-005'::uuid, NULL, 2, 'riasec_interests', 'Performer devant un public (théâtre, danse)', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 21, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb),
('riasec-a-006'::uuid, NULL, 2, 'riasec_interests', 'Exprimer mes idées de manière créative', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 22, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb),
('riasec-a-007'::uuid, NULL, 2, 'riasec_interests', 'Travailler dans un environnement non structuré et flexible', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 23, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb),
('riasec-a-008'::uuid, NULL, 2, 'riasec_interests', 'Développer des concepts originaux et innovants', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 24, true, '{"dimension": "A", "category": "Artistique", "weight": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- DIMENSION 4: SOCIAL (S) - 8 questions
-- ============================================================================

INSERT INTO assessment_questions (id, assessment_id, step_number, section, question_text, question_type, options, "order", required, metadata) VALUES
('riasec-s-001'::uuid, NULL, 2, 'riasec_interests', 'Aider les autres à résoudre leurs problèmes', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 25, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb),
('riasec-s-002'::uuid, NULL, 2, 'riasec_interests', 'Enseigner ou former des personnes', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 26, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb),
('riasec-s-003'::uuid, NULL, 2, 'riasec_interests', 'Conseiller et guider les autres', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 27, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb),
('riasec-s-004'::uuid, NULL, 2, 'riasec_interests', 'Travailler en équipe pour atteindre des objectifs communs', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 28, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb),
('riasec-s-005'::uuid, NULL, 2, 'riasec_interests', 'Prendre soin des personnes (santé, bien-être)', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 29, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb),
('riasec-s-006'::uuid, NULL, 2, 'riasec_interests', 'Organiser des activités de groupe', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 30, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb),
('riasec-s-007'::uuid, NULL, 2, 'riasec_interests', 'Écouter et comprendre les besoins des autres', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 31, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb),
('riasec-s-008'::uuid, NULL, 2, 'riasec_interests', 'Contribuer au bien-être de la communauté', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 32, true, '{"dimension": "S", "category": "Social", "weight": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- DIMENSION 5: ENTERPRISING (E) - 8 questions
-- ============================================================================

INSERT INTO assessment_questions (id, assessment_id, step_number, section, question_text, question_type, options, "order", required, metadata) VALUES
('riasec-e-001'::uuid, NULL, 2, 'riasec_interests', 'Diriger et gérer une équipe', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 33, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb),
('riasec-e-002'::uuid, NULL, 2, 'riasec_interests', 'Vendre des produits ou des services', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 34, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb),
('riasec-e-003'::uuid, NULL, 2, 'riasec_interests', 'Persuader et influencer les autres', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 35, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb),
('riasec-e-004'::uuid, NULL, 2, 'riasec_interests', 'Lancer et développer des projets entrepreneuriaux', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 36, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb),
('riasec-e-005'::uuid, NULL, 2, 'riasec_interests', 'Prendre des décisions stratégiques', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 37, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb),
('riasec-e-006'::uuid, NULL, 2, 'riasec_interests', 'Négocier des accords et des contrats', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 38, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb),
('riasec-e-007'::uuid, NULL, 2, 'riasec_interests', 'Atteindre des objectifs ambitieux', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 39, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb),
('riasec-e-008'::uuid, NULL, 2, 'riasec_interests', 'Prendre des risques calculés pour réussir', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 40, true, '{"dimension": "E", "category": "Entreprenant", "weight": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- DIMENSION 6: CONVENTIONAL (C) - 8 questions
-- ============================================================================

INSERT INTO assessment_questions (id, assessment_id, step_number, section, question_text, question_type, options, "order", required, metadata) VALUES
('riasec-c-001'::uuid, NULL, 2, 'riasec_interests', 'Organiser et classer des informations', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 41, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb),
('riasec-c-002'::uuid, NULL, 2, 'riasec_interests', 'Travailler avec des chiffres et des données', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 42, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb),
('riasec-c-003'::uuid, NULL, 2, 'riasec_interests', 'Suivre des procédures et des règles établies', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 43, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb),
('riasec-c-004'::uuid, NULL, 2, 'riasec_interests', 'Gérer des tâches administratives', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 44, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb),
('riasec-c-005'::uuid, NULL, 2, 'riasec_interests', 'Maintenir des systèmes organisés et efficaces', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 45, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb),
('riasec-c-006'::uuid, NULL, 2, 'riasec_interests', 'Vérifier l''exactitude des informations', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 46, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb),
('riasec-c-007'::uuid, NULL, 2, 'riasec_interests', 'Travailler dans un environnement structuré et prévisible', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 47, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb),
('riasec-c-008'::uuid, NULL, 2, 'riasec_interests', 'Gérer des budgets et des finances', 'likert_scale', '[{"value": 1, "label": "Pas du tout intéressé(e)"},{"value": 2, "label": "Peu intéressé(e)"},{"value": 3, "label": "Moyennement intéressé(e)"},{"value": 4, "label": "Intéressé(e)"},{"value": 5, "label": "Très intéressé(e)"}]', 48, true, '{"dimension": "C", "category": "Conventionnel", "weight": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- MIGRATION COMPLETE - ALL 48 RIASEC QUESTIONS
-- ============================================================================

